version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - JWT_SECRET=your-jwt-secret
      - MONGODB_URI=your-mongodb-uri
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: always
